### ISSUE TITLE
[BUG] something wrong?

### ISSUE THREAD

**Issue by mangic** [Tohrusky/Final2x#11]
win10X64 system.

{"gpuid":0,"inputpath":["C:\\Users\\Administrator\\Downloads\\1644638548ZOQSET.png"],"model":"RealESRGAN","modelscale":4,"modelnoise":0,"outputpath":"C:\\Users\\Administrator\\Downloads","targetscale":0,"tta":false}
2023-07-05 17:30:21.382 | INFO     | __main__:main:56 - projectPATH: C:\Users\Administrator\AppData\Local\Programs\Final2x\resources\app\resources\Final2x-core
2023-07-05 17:30:21.382 | INFO     | __main__:main:67 - config loaded
2023-07-05 17:30:21.395 | INFO     | src.SRFactory.SRBaseClass:_set_sr_n:53 - sr_n set to 1
2023-07-05 17:30:21.396 | INFO     | src.SRFactory.SRBaseClass:__init__:35 - SRBaseClass init
2023-07-05 17:30:21.412 | ERROR    | src.SRFactory.REALESRGAN:__init__:14 - An error has been caught in function '__init__', process 'MainProcess' (18372), thread 'MainThread' (18288):
Traceback (most recent call last):
File "src\SRFactory\REALESRGAN.py", line 20, in _init_SR_class
File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
File "src\SRncnn\REALESRGANncnn.py", line 3, in <module>
File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
File "realesrgan_ncnn_py\__init__.py", line 1, in <module>
File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
File "realesrgan_ncnn_py\realesrgan_ncnn_vulkan.py", line 33, in <module>
ImportError: DLL load failed while importing realesrgan_ncnn_vulkan_wrapper: �Ҳ���ָ����ģ�顣
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "__main__.py", line 82, in <module>
File "__main__.py", line 73, in main
File "src\SRqueue.py", line 23, in SR_queue
File "src\SRFactory\SRFactory.py", line 39, in getSR
> File "src\SRFactory\REALESRGAN.py", line 14, in __init__
File "src\SRFactory\REALESRGAN.py", line 23, in _init_SR_class
ModuleNotFoundError: No module named 'Final2x_core'
2023-07-05 17:30:21.422 | ERROR    | src.SRqueue:SR_queue:23 - An error has been caught in function 'SR_queue', process 'MainProcess' (18372), thread 'MainThread' (18288):
Traceback (most recent call last):
File "src\SRFactory\REALESRGAN.py", line 20, in _init_SR_class
File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
File "src\SRncnn\REALESRGANncnn.py", line 3, in <module>
File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
File "realesrgan_ncnn_py\__init__.py", line 1, in <module>
File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
File "realesrgan_ncnn_py\realesrgan_ncnn_vulkan.py", line 33, in <module>
ImportError: DLL load failed while importing realesrgan_ncnn_vulkan_wrapper: �Ҳ���ָ����ģ�顣
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "__main__.py", line 82, in <module>
File "__main__.py", line 73, in main
> File "src\SRqueue.py", line 23, in SR_queue
File "src\SRFactory\SRFactory.py", line 39, in getSR
File "src\SRFactory\REALESRGAN.py", line 14, in __init__
File "src\SRFactory\REALESRGAN.py", line 23, in _init_SR_class
ModuleNotFoundError: No module named 'Final2x_core'
Traceback (most recent call last):
File "src\SRFactory\REALESRGAN.py", line 20, in _init_SR_class
File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
File "src\SRncnn\REALESRGANncnn.py", line 3, in <module>
File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
File "realesrgan_ncnn_py\__init__.py", line 1, in <module>
File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
File "realesrgan_ncnn_py\realesrgan_ncnn_vulkan.py", line 33, in <module>
ImportError: DLL load failed while importing realesrgan_ncnn_vulkan_wrapper: �Ҳ���ָ����ģ�顣
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "__main__.py", line 82, in <module>
File "__main__.py", line 73, in main
File "src\SRqueue.py", line 23, in SR_queue
File "loguru\_logger.py", line 1251, in catch_wrapper
File "src\SRFactory\SRFactory.py", line 39, in getSR
File "src\SRFactory\REALESRGAN.py", line 14, in __init__
File "loguru\_logger.py", line 1251, in catch_wrapper
File "src\SRFactory\REALESRGAN.py", line 23, in _init_SR_class
ModuleNotFoundError: No module named 'Final2x_core'
[18372] Failed to execute script '__main__' due to unhandled exception!
CLOSE CODE:1

**Comment by Tohrusky** [comment]
显卡驱动没更新，少了vulkan-1.dll，马上会发一个带有这个dll的release

**Comment by Tohrusky** [comment]
https://github.com/Tohrusky/Final2x/releases/tag/2023-07-05
