### ISSUE TITLE
[BUG]  OSError: Read-only file system

### ISSUE THREAD

**Issue by Declarcall** [Tohrusky/Final2x#12]
**Describe the bug**
```
{"gpuid":0,"inputpath":["/home/declarcall/Pictures/Image.jpg"],"model":"RealCUGAN-pro","modelscale":2,"modelnoise":-1,"outputpath":"/home/declarcall/Downloads","targetscale":0,"tta":false}
Traceback (most recent call last):
File "__main__.py", line 87, in <module>
File "__main__.py", line 56, in main
File "loguru/_logger.py", line 776, in add
File "loguru/_file_sink.py", line 194, in __init__
File "loguru/_file_sink.py", line 226, in _create_dirs
File "os.py", line 225, in makedirs
OSError: [Errno 30] Read-only file system: '/tmp/.mount_Final2WbPEaI/resources/app/resources/Final2x-core/logs'
[1745726] Failed to execute script '__main__' due to unhandled exception!
CLOSE CODE:1
```

**To Reproduce**
1. 
```
$ ./Final2x-ubuntu-x64-AppImage.AppImage 
[1745521:0705/204133.620933:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[1745579:0705/204133.875234:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[1745574:0705/204134.123052:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
```
2. Drag a image into 
3. Click "START" button

**Desktop (please complete the following information):**
 - OS:  Ubuntu 20.04
 - Arch:  x64
 - Version: [v1.0.1](https://github.com/Tohrusky/Final2x/releases/tag/2023-07-05)

**Comment by Tohrusky** [comment]
try to ```chmod -R 777```

or us pip version?

**Comment by Tohrusky** [comment]
It should be the problem of AppImage, deb should work
appimage has a lot of s**t

**Comment by Tohrusky** [comment]
https://github.com/Tohrusky/Final2x/actions/runs/5495095304
try this build? I have disabled the log saving @Declarcall
