### ISSUE TITLE
[BUG] DLL load failed while importing cv2

### ISSUE THREAD

**Issue by trigsoft** [Tohrusky/Final2x#122]
### Describe the bug | 描述错误 | BUGの説明
Processing the image will cause an error. 

### To reproduce | 复现步骤 | 再現方法
3. See error

### Context | 运行环境 | バックグラウンド
 - OS: [e.g. Ubuntu 20.04]
 - Arch: [e.g. x64]

### Error log | 报错日志 | ログ
```shell
bootstrap()
File "C:\Users\goalo\AppData\Local\Programs\Final2x\resources\app\resources\Final2x-core\cv2\__init__.py", line 153, in bootstrap
native_module = importlib.import_module("cv2")
File "importlib\__init__.py", line 127, in import_module
applySysPathWorkaround = True
ImportError: DLL load failed while importing cv2: The specified module could not be found.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "__main__.py", line 12, in <module>
ModuleNotFoundError: No module named 'Final2x_core'
[16524] Failed to execute script '__main__' due to unhandled exception!
CLOSE CODE:1
```

### Additional context | 附加内容 | 追加コンテキスト
Add any other context and screenshots to help explain your problem.

**Comment by trigsoft** [comment]
> 环境都不说，谁知道呢

也不等等啊。windows 10.

**Comment by Tohrusky** [comment]
https://github.com/opencv/opencv-python#frequently-asked-questions
