### ISSUE TITLE
[Bug] No image comes out after third time while using TTA.

### ISSUE THREAD

**Issue by Sohaiter** [Tohrusky/Final2x#145]
### Please carefully review each item in the checklist below | 请认真检查以下清单中的每一项 | 以下のチェックリストの各項目を注意深く確認してください

- [X] Searched and didn't find a similar issue | 已经搜索过，没有发现类似issue | 類似の問題が見つかりませんでした
- [X] Searched documentation and didn't find relevant content | 已经搜索过文档，没有发现相关内容 | ドキュメントを検索して関連する内容が見つかりませんでした
- [X] Tried with the latest version and the issue still exists | 已经尝试使用过最新版，问题依旧存在 | 最新バージョンを試しましたが問題は解消されませんでした

### Software Version | 软件版本 | ソフトウェアバージョン

1.15

### Operating System | 操作系统 | オペレーティングシステム

Windows x64

### System Version | 系统版本 | システムバージョン

Win10

### Describe the bug | 描述错误 | BUGの説明

No image comes out after third time while using TTA. 

### To reproduce | 复现步骤 | 再現方法

Each time of  third re-creation. Some times even the second time will disappear as well.

### Error log | 报错日志 | ログ

2023-08-24 11:00:52.088 | INFO     | src.utils.progressLog:printProgress:34 - Processing------[ 50.0% ]
2023-08-24 11:01:00.043 | ERROR    | src.SRFactory.SRBaseClass:process:78 - An error has been caught in function 'process', process 'MainProcess' (24248), thread 'MainThread' (4188):
Traceback (most recent call last):
File "__main__.py", line 88, in <module>
File "__main__.py", line 79, in main
File "src\SRqueue.py", line 74, in SR_queue
> File "src\SRFactory\SRBaseClass.py", line 78, in process
File "src\SRFactory\SRBaseClass.py", line 96, in _process_n
File "realesrgan_ncnn_py\realesrgan_ncnn_vulkan.py", line 172, in process_cv2
MemoryError
2023-08-24 11:01:00.662 | ERROR    | src.SRFactory.SRBaseClass:process:79 - An error has been caught in function 'process', process 'MainProcess' (24248), thread 'MainThread' (4188):
Traceback (most recent call last):
File "__main__.py", line 88, in <module>
File "__main__.py", line 79, in main
File "src\SRqueue.py", line 74, in SR_queue
> File "src\SRFactory\SRBaseClass.py", line 79, in process
File "src\SRFactory\SRBaseClass.py", line 89, in _process_downscale
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4062: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
Traceback (most recent call last):
File "__main__.py", line 88, in <module>
File "__main__.py", line 79, in main
File "src\SRqueue.py", line 84, in SR_queue
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:1109: error: (-215:Assertion failed) !image.empty() in function 'cv::imencode'
[24248] Failed to execute script '__main__' due to unhandled exception!

**Comment by Tohrusky** [comment]
It seems process failed in SR net and return None. Try update your GPU driver or use CPU.
When TTA off, it works?

**Comment by Sohaiter** [comment]
Well, I updated both CPU and GPU drivers, turned off the TTA, and received with a image with black lower half in second run and a log with no ERROR. Nothing changed. And I had tired both CPU and GPU mode. Do you have any idea about what is going on?
2023-08-26 15:29:30.620 | INFO     | src.utils.progressLog:printProgress:34 - Processing------[ 100.0% ]
2023-08-26 15:29:58.336 | SUCCESS  | src.SRqueue:SR_queue:86 - ______Process_Completed______: C:\Users\Abiga\Desktop\my Vergil\outputs\outputs\2x-2x-_20230821164411(1).png
2023-08-26 15:29:59.087 | SUCCESS  | __main__:main:81 - ______SR_COMPLETED______
CLOSE CODE:3221226505

> It seems process failed in SR net and return None. Try update your GPU driver or use CPU. When TTA off, it works?

**Comment by Tohrusky** [comment]
Hello! your issue has been closed because it has been inactive for a long time.

你好，你的 issue 因为长时间不活跃而被自动关闭。

こんにちは、お問い合わせは長期間活動がないため、閉じられました。
