### ISSUE TITLE
错误报告

### ISSUE THREAD

**Issue by Rashomon0711** [Tohrusky/Final2x#203]
### Please carefully review each item in the checklist below | 请认真检查以下清单中的每一项 | 以下のチェックリストの各項目を注意深く確認してください

- [ ] Searched and didn't find a similar issue | 已经搜索过，没有发现类似issue | 類似の問題が見つかりませんでした
- [ ] Searched documentation and didn't find relevant content | 已经搜索过文档，没有发现相关内容 | ドキュメントを検索して関連する内容が見つかりませんでした
- [ ] Tried with the latest version and the issue still exists | 已经尝试使用过最新版，问题依旧存在 | 最新バージョンを試しましたが問題は解消されませんでした

### Software Version | 软件版本 | ソフトウェアバージョン

1.1.5

### Operating System | 操作系统 | オペレーティングシステム

Windows x64

### System Version | 系统版本 | システムバージョン

22H2

### Describe the bug | 描述错误 | BUGの説明

图片处理失败
![360截图20231014095430796](https://github.com/Tohrusky/Final2x/assets/114818954/9e40b54a-1cd7-4969-8381-fd56d7403750)

### To reproduce | 复现步骤 | 再現方法

1. 打开final2x，选择模型和放大倍数
2. 将图片拖拽到主界面
3. 显示“处理失败，请点击日志查看错误信息”
4. 之前可以正常使用，突然就不行了。

### Error log | 报错日志 | ログ

```
[{"label":"CPU: Core™ i5-10600KF","value":-1},{"label":"GPU 0: NVIDIA GeForce RTX 3070","value":0},{"label":"GPU: Auto","value":114514}]
{"gpuid":0,"inputpath":["F:\\Pictures\\hya.jpg"],"model":"RealESRGAN","modelscale":4,"modelnoise":0,"outputpath":"C:\\Users\\dio07\\Desktop","targetscale":0,"tta":false}
2023-10-14 09:46:46.628 | INFO     | __main__:main:58 - projectPATH: D:\Program Files\Final2x\resources\app\resources\Final2x-core
2023-10-14 09:46:46.628 | INFO     | __main__:main:71 - config loaded
2023-10-14 09:46:46.628 | INFO     | src.SRFactory.SRBaseClass:_set_sr_n:53 - sr_n set to 1
2023-10-14 09:46:46.628 | INFO     | src.SRFactory.SRBaseClass:__init__:35 - SRBaseClass init
vkCreateInstance failed -9
vkCreateInstance failed -9
2023-10-14 09:46:46.728 | ERROR    | src.SRFactory.REALESRGAN:__init__:14 - An error has been caught in function '__init__', process 'MainProcess' (18180), thread 'MainThread' (2860):
Traceback (most recent call last):
File "__main__.py", line 88, in <module>
File "__main__.py", line 79, in main
File "src\SRqueue.py", line 23, in SR_queue
File "src\SRFactory\SRFactory.py", line 39, in getSR
> File "src\SRFactory\REALESRGAN.py", line 14, in __init__
File "src\SRFactory\REALESRGAN.py", line 65, in _init_SR_class
File "realesrgan_ncnn_py\realesrgan_ncnn_vulkan.py", line 68, in __init__
File "src\SRncnn\REALESRGANncnn.py", line 46, in load
File "realesrgan_ncnn_py\realesrgan_ncnn_vulkan.py", line 79, in _set_parameters
RuntimeError: Caught an unknown exception!
2023-10-14 09:46:46.728 | ERROR    | src.SRqueue:SR_queue:23 - An error has been caught in function 'SR_queue', process 'MainProcess' (18180), thread 'MainThread' (2860):
Traceback (most recent call last):
File "__main__.py", line 88, in <module>
File "__main__.py", line 79, in main
> File "src\SRqueue.py", line 23, in SR_queue
File "src\SRFactory\SRFactory.py", line 39, in getSR
File "src\SRFactory\REALESRGAN.py", line 14, in __init__
File "src\SRFactory\REALESRGAN.py", line 65, in _init_SR_class
File "realesrgan_ncnn_py\realesrgan_ncnn_vulkan.py", line 68, in __init__
File "src\SRncnn\REALESRGANncnn.py", line 46, in load
File "realesrgan_ncnn_py\realesrgan_ncnn_vulkan.py", line 79, in _set_parameters
RuntimeError: Caught an unknown exception!
Traceback (most recent call last):
File "__main__.py", line 88, in <module>
File "__main__.py", line 79, in main
File "src\SRqueue.py", line 23, in SR_queue
File "loguru\_logger.py", line 1251, in catch_wrapper
File "src\SRFactory\SRFactory.py", line 39, in getSR
File "src\SRFactory\REALESRGAN.py", line 14, in __init__
File "loguru\_logger.py", line 1251, in catch_wrapper
File "src\SRFactory\REALESRGAN.py", line 65, in _init_SR_class
File "realesrgan_ncnn_py\realesrgan_ncnn_vulkan.py", line 68, in __init__
File "src\SRncnn\REALESRGANncnn.py", line 46, in load
File "realesrgan_ncnn_py\realesrgan_ncnn_vulkan.py", line 79, in _set_parameters
RuntimeError: Caught an unknown exception!
[18180] Failed to execute script '__main__' due to unhandled exception!
CLOSE CODE:3221225477
```

**Comment by Tohrusky** [comment]
Hello @Rashomon0711, your issue has been closed because the title does not conform to our specification.

你好 @Rashomon0711，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为标题不符合规范而被自动关闭。

こんにちは、@Rashomon0711さん、タイトルが仕様に準拠していないため、ご提案いただいた問題はクローズされました。
