### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ginitaimeiyty** [Tohrusky/Final2x#251]
### Please carefully review each item in the checklist below | 请认真检查以下清单中的每一项 | 以下のチェックリストの各項目を注意深く確認してください

- [ ] Searched and didn't find a similar issue | 已经搜索过，没有发现类似issue | 類似の問題が見つかりませんでした
- [X] Searched documentation and didn't find relevant content | 已经搜索过文档，没有发现相关内容 | ドキュメントを検索して関連する内容が見つかりませんでした
- [X] Tried with the latest version and the issue still exists | 已经尝试使用过最新版，问题依旧存在 | 最新バージョンを試しましたが問題は解消されませんでした

### Software Version | 软件版本 | ソフトウェアバージョン

1.1.5

### Operating System | 操作系统 | オペレーティングシステム

Windows x64

### System Version | 系统版本 | システムバージョン

Windows 10专业版22H219045	

### Describe the bug | 描述错误 | BUGの説明

图片处理失败

### To reproduce | 复现步骤 | 再現方法

1.打开final2x，选择模型和放大倍数
2.点击到此上传文件，选择文件上传（有时还存在图片无法拖拽的问题）
3.显示“处理失败，请点击日志查看错误信息”
PS：换了几个模型都无法处理 

### Error log | 报错日志 | ログ

```
your error log
```

0%
GPU 2: NVIDIA GeForce RTX 4060 Laptop GPU
Waifu2x-upconv_7_anime_style_art_rgb
2
3
0.2
E:\

Log
[{"label":"CPU: Ryzen 9 7940H w/ Radeon 780M Graphics","value":-1},{"label":"GPU 0: OrayIddDriver Device","value":0},{"label":"GPU 1: AMD Radeon 780M Graphics","value":1},{"label":"GPU 2: NVIDIA GeForce RTX 4060 Laptop GPU","value":2},{"label":"GPU: Auto","value":114514}]
{"gpuid":2,"inputpath":["C:\\Users\\19963\\Desktop\\ab0950c1c91cc8df228a1c9056c881d.png"],"model":"Waifu2x-upconv_7_anime_style_art_rgb","modelscale":2,"modelnoise":3,"outputpath":"E:\\","targetscale":0.2,"tta":false}
2023-11-28 16:27:52.859 | INFO     | __main__:main:58 - projectPATH: C:\Users\19963\AppData\Local\Programs\Final2x\resources\app\resources\Final2x-core
2023-11-28 16:27:52.859 | INFO     | __main__:main:71 - config loaded
2023-11-28 16:27:52.859 | INFO     | src.SRFactory.SRBaseClass:_set_sr_n:53 - sr_n set to 1
2023-11-28 16:27:52.859 | INFO     | src.SRFactory.SRBaseClass:__init__:35 - SRBaseClass init
[0 NVIDIA GeForce RTX 4060 Laptop GPU]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 4060 Laptop GPU]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 4060 Laptop GPU]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 4060 Laptop GPU]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[1 AMD Radeon 780M Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[1]
[1 AMD Radeon 780M Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 AMD Radeon 780M Graphics]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 AMD Radeon 780M Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1
2023-11-28 16:27:53.263 | ERROR    | src.SRFactory.WAIFU2X:__init__:14 - An error has been caught in function '__init__', process 'MainProcess' (16612), thread 'MainThread' (29344):
Traceback (most recent call last):
File "__main__.py", line 88, in <module>
File "__main__.py", line 79, in main
File "src\SRqueue.py", line 23, in SR_queue
File "src\SRFactory\SRFactory.py", line 49, in getSR
> File "src\SRFactory\WAIFU2X.py", line 14, in __init__
File "src\SRFactory\WAIFU2X.py", line 72, in _init_SR_class
File "waifu2x_ncnn_py\waifu2x_ncnn_vulkan.py", line 79, in __init__
File "waifu2x_ncnn_py\waifu2x_ncnn_vulkan.py", line 94, in set_parameters
RuntimeError: Caught an unknown exception!
2023-11-28 16:27:53.264 | ERROR    | src.SRqueue:SR_queue:23 - An error has been caught in function 'SR_queue', process 'MainProcess' (16612), thread 'MainThread' (29344):
Traceback (most recent call last):
File "__main__.py", line 88, in <module>
File "__main__.py", line 79, in main
> File "src\SRqueue.py", line 23, in SR_queue
File "src\SRFactory\SRFactory.py", line 49, in getSR
File "src\SRFactory\WAIFU2X.py", line 14, in __init__
File "src\SRFactory\WAIFU2X.py", line 72, in _init_SR_class
File "waifu2x_ncnn_py\waifu2x_ncnn_vulkan.py", line 79, in __init__
File "waifu2x_ncnn_py\waifu2x_ncnn_vulkan.py", line 94, in set_parameters
RuntimeError: Caught an unknown exception!
Traceback (most recent call last):
File "__main__.py", line 88, in <module>
File "__main__.py", line 79, in main
File "src\SRqueue.py", line 23, in SR_queue
File "loguru\_logger.py", line 1251, in catch_wrapper
File "src\SRFactory\SRFactory.py", line 49, in getSR
File "src\SRFactory\WAIFU2X.py", line 14, in __init__
File "loguru\_logger.py", line 1251, in catch_wrapper
File "src\SRFactory\WAIFU2X.py", line 72, in _init_SR_class
File "waifu2x_ncnn_py\waifu2x_ncnn_vulkan.py", line 79, in __init__
File "waifu2x_ncnn_py\waifu2x_ncnn_vulkan.py", line 94, in set_parameters
RuntimeError: Caught an unknown exception!
[16612] Failed to execute script '__main__' due to unhandled exception!
CLOSE CODE:3221225477

### Additional context | 附加内容 | 追加コンテキスト

![Uploading 屏幕截图 2023-11-28 163025.png…]()

**Comment by Tohrusky** [comment]
Hello @ginitaimeiyty, your issue has been closed because the title does not conform to our specification.

你好 @ginitaimeiyty，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为标题不符合规范而被自动关闭。

こんにちは、@ginitaimeiytyさん、タイトルが仕様に準拠していないため、ご提案いただいた問題はクローズされました。
