### ISSUE TITLE
[BUG]It works fine when I use cpu, but I get an error when using gpu.

### ISSUE THREAD

**Issue by mangic** [Tohrusky/Final2x#28]
### Describe the bug | 描述错误 | BUGの説明
**It works fine when I use cpu, but I get an error when using gpu.**
![image](https://github.com/Tohrusky/Final2x/assets/33594145/905bc682-0634-4539-a4f0-7fed5c29c588)
![image](https://github.com/Tohrusky/Final2x/assets/33594145/e2402301-0b02-44ba-915c-76c5ac626e83)

### Context | 运行环境 | バックグラウンド
 - system: [win7_X64]

### Error log | 报错日志 | ログ
{"gpuid":0,"inputpath":["C:\\Users\\Administrator\\Downloads\\微信图片_20230708143021.jpg"],"model":"RealCUGAN-pro","modelscale":2,"modelnoise":0,"outputpath":"C:\\Users\\Administrator\\Downloads","targetscale":0,"tta":false}
2023-07-08 14:55:22.113 | INFO     | __main__:main:57 - projectPATH: C:\Users\Administrator\AppData\Local\Programs\Final2x\resources\app\resources\Final2x-core
2023-07-08 14:55:22.114 | INFO     | __main__:main:70 - config loaded
2023-07-08 14:55:22.114 | INFO     | src.SRFactory.SRBaseClass:_set_sr_n:53 - sr_n set to 1
2023-07-08 14:55:22.114 | INFO     | src.SRFactory.SRBaseClass:__init__:35 - SRBaseClass init
vkCreateInstance failed -9
vkCreateInstance failed -9
2023-07-08 14:55:22.138 | ERROR    | src.SRFactory.REALCUGAN:__init__:14 - An error has been caught in function '__init__', process 'MainProcess' (16896), thread 'MainThread' (9556):
Traceback (most recent call last):
File "__main__.py", line 87, in <module>
File "__main__.py", line 78, in main
File "src\SRqueue.py", line 23, in SR_queue
File "src\SRFactory\SRFactory.py", line 26, in getSR
> File "src\SRFactory\REALCUGAN.py", line 14, in __init__
File "src\SRFactory\REALCUGAN.py", line 61, in _init_SR_class
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 78, in __init__
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 96, in _set_parameters
RuntimeError: Caught an unknown exception!
2023-07-08 14:55:22.142 | ERROR    | src.SRqueue:SR_queue:23 - An error has been caught in function 'SR_queue', process 'MainProcess' (16896), thread 'MainThread' (9556):
Traceback (most recent call last):
File "__main__.py", line 87, in <module>
File "__main__.py", line 78, in main
> File "src\SRqueue.py", line 23, in SR_queue
File "src\SRFactory\SRFactory.py", line 26, in getSR
File "src\SRFactory\REALCUGAN.py", line 14, in __init__
File "src\SRFactory\REALCUGAN.py", line 61, in _init_SR_class
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 78, in __init__
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 96, in _set_parameters
RuntimeError: Caught an unknown exception!
Traceback (most recent call last):
File "__main__.py", line 87, in <module>
File "__main__.py", line 78, in main
File "src\SRqueue.py", line 23, in SR_queue
File "loguru\_logger.py", line 1251, in catch_wrapper
File "src\SRFactory\SRFactory.py", line 26, in getSR
File "src\SRFactory\REALCUGAN.py", line 14, in __init__
File "loguru\_logger.py", line 1251, in catch_wrapper
File "src\SRFactory\REALCUGAN.py", line 61, in _init_SR_class
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 78, in __init__
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 96, in _set_parameters
RuntimeError: Caught an unknown exception!
[16896] Failed to execute script '__main__' due to unhandled exception!
CLOSE CODE:3221225477

**Comment by Tohrusky** [comment]
win7竟然能用ui吗... Electron23后说是不支持了
[你的显卡太老了，不支持vulkan](https://community.intel.com/t5/Graphics/Vulkan-support-for-Intel-HD-4600-on-I7-4790/td-p/1205436?profile.language=zh-TW)
