### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by live4fun** [Tohrusky/Final2x#29]
### Context | 运行环境 | バックグラウンド
 - OS: Windows 10
 - Arch: [e.g. x64]
 - 
- Device: GPU: NVIDIA GeForce GTX 1070
- Model: RealCUGAN-pro

### Error log | 报错日志 | ログ
0%
GPU: NVIDIA GeForce GTX 1070
RealCUGAN-pro
2
0
0
G:\

Log
{"gpuid":1,"inputpath":["G:\\1.jpg"],"model":"RealCUGAN-pro","modelscale":2,"modelnoise":0,"outputpath":"G:\\","targetscale":0,"tta":true}
2023-07-08 16:23:38.663 | INFO     | __main__:main:57 - projectPATH: F:\Downloads\Final2x\resources\app\resources\Final2x-core
2023-07-08 16:23:38.663 | INFO     | __main__:main:70 - config loaded
2023-07-08 16:23:38.663 | INFO     | src.SRFactory.SRBaseClass:_set_sr_n:53 - sr_n set to 1
2023-07-08 16:23:38.664 | INFO     | src.SRFactory.SRBaseClass:__init__:35 - SRBaseClass init
[0 NVIDIA GeForce GTX 1070]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce GTX 1070]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce GTX 1070]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 NVIDIA GeForce GTX 1070]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
2023-07-08 16:23:38.765 | ERROR    | src.SRFactory.REALCUGAN:__init__:14 - An error has been caught in function '__init__', process 'MainProcess' (21164), thread 'MainThread' (19000):
Traceback (most recent call last):
File "__main__.py", line 87, in <module>
File "__main__.py", line 78, in main
File "src\SRqueue.py", line 23, in SR_queue
File "src\SRFactory\SRFactory.py", line 26, in getSR
> File "src\SRFactory\REALCUGAN.py", line 14, in __init__
File "src\SRFactory\REALCUGAN.py", line 61, in _init_SR_class
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 78, in __init__
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 96, in _set_parameters
RuntimeError: Caught an unknown exception!
2023-07-08 16:23:38.768 | ERROR    | src.SRqueue:SR_queue:23 - An error has been caught in function 'SR_queue', process 'MainProcess' (21164), thread 'MainThread' (19000):
Traceback (most recent call last):
File "__main__.py", line 87, in <module>
File "__main__.py", line 78, in main
> File "src\SRqueue.py", line 23, in SR_queue
File "src\SRFactory\SRFactory.py", line 26, in getSR
File "src\SRFactory\REALCUGAN.py", line 14, in __init__
File "src\SRFactory\REALCUGAN.py", line 61, in _init_SR_class
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 78, in __init__
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 96, in _set_parameters
RuntimeError: Caught an unknown exception!
Traceback (most recent call last):
File "__main__.py", line 87, in <module>
File "__main__.py", line 78, in main
File "src\SRqueue.py", line 23, in SR_queue
File "loguru\_logger.py", line 1251, in catch_wrapper
File "src\SRFactory\SRFactory.py", line 26, in getSR
File "src\SRFactory\REALCUGAN.py", line 14, in __init__
File "loguru\_logger.py", line 1251, in catch_wrapper
File "src\SRFactory\REALCUGAN.py", line 61, in _init_SR_class
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 78, in __init__
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 96, in _set_parameters
RuntimeError: Caught an unknown exception!
[21164] Failed to execute script '__main__' due to unhandled exception!
CLOSE CODE:3221225477

**Comment by Tohrusky** [comment]
Hello @live4fun, your issue has been closed because it does not conform to our issue template. 

你好 @live4fun，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合模版格式而被自动关闭。

こんにちは、@live4funさん、あなたの問題は、弊社の問題テンプレートに準拠していないため、クローズされました。

**Comment by Tohrusky** [comment]
Hello @live4fun, your issue has been closed because because the title does not conform to our specification.

你好 @live4fun，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为标题不符合规范而被自动关闭。

こんにちは、@live4funさん、タイトルが仕様に準拠していないため、ご提案いただいた問題はクローズされました。

**Comment by Tohrusky** [comment]
Hello @live4fun, your issue has been closed because it does not conform to our issue template. 

你好 @live4fun，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合模版格式而被自动关闭。

こんにちは、@live4funさん、あなたの問題は、弊社の問題テンプレートに準拠していないため、クローズされました。
