### ISSUE TITLE
[BUG]Cannot use the Nvidia GTX 1070 graphics card.

### ISSUE THREAD

**Issue by live4fun** [Tohrusky/Final2x#30]
### Describe the bug | 描述错误 | BUGの説明
Cannot use the graphics card.

### To reproduce | 复现步骤 | 再現方法 
1. Go to 'Device'
2. Click on ' choose an graphics card'
3. See error in log

### Context | 运行环境 | バックグラウンド
 - OS: [Windows 10 22H2]
 - Arch: [e.g. x64]

### Error log | 报错日志 | ログ
```shell
0%
GPU: NVIDIA GeForce GTX 1070
Waifu2x-upconv_7_photo
2
0
0
G:\


Log
{"gpuid":1,"inputpath":["G:\\1.jpg"],"model":"Waifu2x-upconv_7_photo","modelscale":2,"modelnoise":0,"outputpath":"G:\\","targetscale":0,"tta":true}
2023-07-08 16:42:13.430 | INFO     | __main__:main:57 - projectPATH: F:\Downloads\Final2x\resources\app\resources\Final2x-core
2023-07-08 16:42:13.431 | INFO     | __main__:main:70 - config loaded
2023-07-08 16:42:13.431 | INFO     | src.SRFactory.SRBaseClass:_set_sr_n:53 - sr_n set to 1
2023-07-08 16:42:13.431 | INFO     | src.SRFactory.SRBaseClass:__init__:35 - SRBaseClass init
[0 NVIDIA GeForce GTX 1070]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce GTX 1070]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce GTX 1070]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 NVIDIA GeForce GTX 1070]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
2023-07-08 16:42:13.532 | ERROR    | src.SRFactory.WAIFU2X:__init__:14 - An error has been caught in function '__init__', process 'MainProcess' (1924), thread 'MainThread' (16040):
Traceback (most recent call last):
File "__main__.py", line 87, in <module>
File "__main__.py", line 78, in main
File "src\SRqueue.py", line 23, in SR_queue
File "src\SRFactory\SRFactory.py", line 49, in getSR
> File "src\SRFactory\WAIFU2X.py", line 14, in __init__
File "src\SRFactory\WAIFU2X.py", line 72, in _init_SR_class
File "waifu2x_ncnn_py\waifu2x_ncnn_vulkan.py", line 79, in __init__
File "waifu2x_ncnn_py\waifu2x_ncnn_vulkan.py", line 94, in set_parameters
RuntimeError: Caught an unknown exception!
2023-07-08 16:42:13.535 | ERROR    | src.SRqueue:SR_queue:23 - An error has been caught in function 'SR_queue', process 'MainProcess' (1924), thread 'MainThread' (16040):
Traceback (most recent call last):
File "__main__.py", line 87, in <module>
File "__main__.py", line 78, in main
> File "src\SRqueue.py", line 23, in SR_queue
File "src\SRFactory\SRFactory.py", line 49, in getSR
File "src\SRFactory\WAIFU2X.py", line 14, in __init__
File "src\SRFactory\WAIFU2X.py", line 72, in _init_SR_class
File "waifu2x_ncnn_py\waifu2x_ncnn_vulkan.py", line 79, in __init__
File "waifu2x_ncnn_py\waifu2x_ncnn_vulkan.py", line 94, in set_parameters
RuntimeError: Caught an unknown exception!
Traceback (most recent call last):
File "__main__.py", line 87, in <module>
File "__main__.py", line 78, in main
File "src\SRqueue.py", line 23, in SR_queue
File "loguru\_logger.py", line 1251, in catch_wrapper
File "src\SRFactory\SRFactory.py", line 49, in getSR
File "src\SRFactory\WAIFU2X.py", line 14, in __init__
File "loguru\_logger.py", line 1251, in catch_wrapper
File "src\SRFactory\WAIFU2X.py", line 72, in _init_SR_class
File "waifu2x_ncnn_py\waifu2x_ncnn_vulkan.py", line 79, in __init__
File "waifu2x_ncnn_py\waifu2x_ncnn_vulkan.py", line 94, in set_parameters
RuntimeError: Caught an unknown exception!
[1924] Failed to execute script '__main__' due to unhandled exception!
CLOSE CODE:3221225477
```

### Additional context | 附加内容 | 追加コンテキスト
Add any other context and screenshots to help explain your problem.

**Comment by Tohrusky** [comment]
你只有一张卡支持vulkan，所以gpu得选0号
下一个版本还是出个GPU Auto吧，默认0

**Comment by Tohrusky** [comment]
[done](https://github.com/Tohrusky/Final2x/pull/26/commits/3eadb71dec658549aaf1a9e1f86e371a55032370)

**Comment by live4fun** [comment]
如何设置GPU选0号

**Comment by Tohrusky** [comment]
数数呀，第一个gpu就是0

**Comment by live4fun** [comment]
Final2x设置界面中，Device选项里只有1个CPU和1个GPU:NVIDIA GeForce GTX 1070可选，我选择GPU,点击开始后显示错误。不知道你上面说的GPU选0号是什么意思

**Comment by Tohrusky** [comment]
那确实有点奇怪，只有一张显卡gpuid应该是0才对
重启一下软件，ctrl+shift+i呼出调试看看返回的device Array长啥样
