### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by DaliBerr** [Tohrusky/Final2x#324]
### Please carefully review each item in the checklist below | 请认真检查以下清单中的每一项 | 以下のチェックリストの各項目を注意深く確認してください

- [X] Searched and didn't find a similar issue | 已经搜索过，没有发现类似issue | 類似の問題が見つかりませんでした
- [X] Searched documentation and didn't find relevant content | 已经搜索过文档，没有发现相关内容 | ドキュメントを検索して関連する内容が見つかりませんでした
- [X] Tried with the latest version and the issue still exists | 已经尝试使用过最新版，问题依旧存在 | 最新バージョンを試しましたが問題は解消されませんでした

### Software Version | 软件版本 | ソフトウェアバージョン

1.2.00

### Operating System | 操作系统 | オペレーティングシステム

Windows x64

### System Version | 系统版本 | システムバージョン

Windows 11 23H2

### Describe the bug | 描述错误 | BUGの説明

转换图片输入后即报错 
尝试过tif png jpg都会出现

### To reproduce | 复现步骤 | 再現方法

初次安装后放入图片立即出现报错

### Error log | 报错日志 | ログ

2024-01-18 21:54:39.630 | ERROR    | Final2x_core.src.SRFactory.SRBaseClass:process:77 - An error has been caught in function 'process', process 'MainProcess' (6796), thread 'MainThread' (6000):
Traceback (most recent call last):
File "Final2x_core\__main__.py", line 82, in <module>
File "Final2x_core\__main__.py", line 73, in main
File "Final2x_core\src\SRqueue.py", line 71, in SR_queue
> File "Final2x_core\src\SRFactory\SRBaseClass.py", line 77, in process
File "Final2x_core\src\SRFactory\SRBaseClass.py", line 95, in _process_n
File "realesrgan_ncnn_py\realesrgan_ncnn_vulkan.py", line 181, in process_cv2
cv2.error: OpenCV(4.8.1) d:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function '__cdecl cv::impl::`anonymous-namespace'::CvtHelper<struct cv::impl::`anonymous namespace'::Set<3,4,-1>,struct cv::impl::A0xd8611878::Set<3,4,-1>,struct cv::impl::A0xd8611878::Set<0,2,5>,3>::CvtHelper(const class cv::_InputArray &,const class cv::_OutputArray &,int)'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 6
Traceback (most recent call last):
File "Final2x_core\__main__.py", line 82, in <module>
File "Final2x_core\__main__.py", line 73, in main
File "Final2x_core\src\SRqueue.py", line 81, in SR_queue
cv2.error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:1113: error: (-215:Assertion failed) !image.empty() in function 'cv::imencode'
[6796] Failed to execute script '__main__' due to unhandled exception!
CLOSE CODE:3221226505

**Comment by Tohrusky** [comment]
Hello @DaliBerr, your issue has been closed because the title does not conform to our specification.

你好 @DaliBerr，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为标题不符合规范而被自动关闭。

こんにちは、@DaliBerrさん、タイトルが仕様に準拠していないため、ご提案いただいた問題はクローズされました。
