### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by chenxqiyu** [Tohrusky/Final2x#39]
### To reproduce | 复现步骤 | 再現方法 
3. See error

### Context | 运行环境 | バックグラウンド
 - OS: [e.g. Ubuntu 20.04]
 - Arch: [e.g. x64]

### Error log | 报错日志 | ログ
```shell
{"gpuid":1,"inputpath":["C:\\Users\\chenx\\Desktop\\Snipaste_2023-07-02_08-04-43.png"],"model":"RealCUGAN-pro","modelscale":2,"modelnoise":-1,"outputpath":"C:\\Users\\chenx\\Desktop","targetscale":0,"tta":false}
2023-07-10 21:08:18.400 | INFO     | __main__:main:58 - projectPATH: C:\Users\chenx\AppData\Local\Programs\Final2x\resources\app\resources\Final2x-core
2023-07-10 21:08:18.400 | INFO     | __main__:main:71 - config loaded
2023-07-10 21:08:18.400 | INFO     | src.SRFactory.SRBaseClass:_set_sr_n:53 - sr_n set to 1
2023-07-10 21:08:18.401 | INFO     | src.SRFactory.SRBaseClass:__init__:35 - SRBaseClass init
[0 NVIDIA GeForce RTX 4070 Ti]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 4070 Ti]  bugsbn1=0  bugbilz=65  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 4070 Ti]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 4070 Ti]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
2023-07-10 21:08:18.522 | ERROR    | src.SRFactory.REALCUGAN:__init__:14 - An error has been caught in function '__init__', process 'MainProcess' (26452), thread 'MainThread' (14184):
Traceback (most recent call last):
File "__main__.py", line 88, in <module>
File "__main__.py", line 79, in main
File "src\SRqueue.py", line 23, in SR_queue
File "src\SRFactory\SRFactory.py", line 26, in getSR
> File "src\SRFactory\REALCUGAN.py", line 14, in __init__
File "src\SRFactory\REALCUGAN.py", line 61, in _init_SR_class
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 78, in __init__
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 96, in _set_parameters
RuntimeError: Caught an unknown exception!
2023-07-10 21:08:18.524 | ERROR    | src.SRqueue:SR_queue:23 - An error has been caught in function 'SR_queue', process 'MainProcess' (26452), thread 'MainThread' (14184):
Traceback (most recent call last):
File "__main__.py", line 88, in <module>
File "__main__.py", line 79, in main
> File "src\SRqueue.py", line 23, in SR_queue
File "src\SRFactory\SRFactory.py", line 26, in getSR
File "src\SRFactory\REALCUGAN.py", line 14, in __init__
File "src\SRFactory\REALCUGAN.py", line 61, in _init_SR_class
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 78, in __init__
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 96, in _set_parameters
RuntimeError: Caught an unknown exception!
Traceback (most recent call last):
File "__main__.py", line 88, in <module>
File "__main__.py", line 79, in main
File "src\SRqueue.py", line 23, in SR_queue
File "loguru\_logger.py", line 1251, in catch_wrapper
File "src\SRFactory\SRFactory.py", line 26, in getSR
File "src\SRFactory\REALCUGAN.py", line 14, in __init__
File "loguru\_logger.py", line 1251, in catch_wrapper
File "src\SRFactory\REALCUGAN.py", line 61, in _init_SR_class
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 78, in __init__
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 96, in _set_parameters
RuntimeError: Caught an unknown exception!
[26452] Failed to execute script '__main__' due to unhandled exception!
CLOSE CODE:3221225477
```

### Additional context | 附加内容 | 追加コンテキスト
Add any other context and screenshots to help explain your problem.

**Comment by Tohrusky** [comment]
Hello @chenxqiyu, your issue has been closed because the title does not conform to our specification.

你好 @chenxqiyu，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为标题不符合规范而被自动关闭。

こんにちは、@chenxqiyuさん、タイトルが仕様に準拠していないため、ご提案いただいた問題はクローズされました。

**Comment by chenxqiyu** [comment]
add
