### ISSUE TITLE
[Bug]CLOSE CODE:3221225477

### ISSUE THREAD

**Issue by KlasFrosty** [Tohrusky/Final2x#473]
### Please carefully review each item in the checklist below | 请认真检查以下清单中的每一项 | 以下のチェックリストの各項目を注意深く確認してください

- [X] Searched and didn't find a similar issue | 已经搜索过，没有发现类似issue | 類似の問題が見つかりませんでした
- [x] Searched documentation and didn't find relevant content | 已经搜索过文档，没有发现相关内容 | ドキュメントを検索して関連する内容が見つかりませんでした
- [X] Tried with the latest version and the issue still exists | 已经尝试使用过最新版，问题依旧存在 | 最新バージョンを試しましたが問題は解消されませんでした

### Software Version | 软件版本 | ソフトウェアバージョン

1.2.0

### Operating System | 操作系统 | オペレーティングシステム

Windows x64

### System Version | 系统版本 | システムバージョン

10

### Describe the bug | 描述错误 | BUGの説明

When I try to upscale any photo 

❌Processing failed
Please click on the log to view the error message

I'm getting an error. Log's here:

### To reproduce | 复现步骤 | 再現方法

Processing failed
Please click on the log to view the error message

### Error log | 报错日志 | ログ

```
[{"label":"CPU: Ryzen 5 3600X 6-Core Processor","value":-1},{"label":"GPU 0: Parsec Virtual Display Adapter","value":0},{"label":"GPU 1: NVIDIA GeForce GTX 1660 SUPER","value":1},{"label":"GPU: Auto","value":114514}]
{"gpuid":1,"inputpath":["C:\\Users\\bibim\\Downloads\\1717617926676.jpg"],"model":"RealCUGAN-se","modelscale":2,"modelnoise":0,"outputpath":"C:\\Users\\bibim\\Downloads","targetscale":0.6,"tta":false}
2024-06-08 14:33:54.334 | INFO     | __main__:main:55 - projectPATH: C:\Users\bibim\AppData\Local\Programs\Final2x\resources\app\resources\Final2x-core
2024-06-08 14:33:54.334 | INFO     | __main__:main:70 - config loaded
2024-06-08 14:33:54.334 | DEBUG    | __main__:main:71 - C:\Users\bibim\Downloads
2024-06-08 14:33:54.334 | INFO     | Final2x_core.src.SRFactory.SRBaseClass:_set_sr_n:50 - sr_n set to 1
2024-06-08 14:33:54.334 | INFO     | Final2x_core.src.SRFactory.SRBaseClass:__init__:32 - SRBaseClass init
vkCreateInstance failed -9
vkCreateInstance failed -9
2024-06-08 14:33:54.362 | ERROR    | Final2x_core.src.SRFactory.REALCUGAN:__init__:9 - An error has been caught in function '__init__', process 'MainProcess' (6272), thread 'MainThread' (7236):
Traceback (most recent call last):
File "Final2x_core\__main__.py", line 82, in <module>
File "Final2x_core\__main__.py", line 73, in main
File "Final2x_core\src\SRqueue.py", line 20, in SR_queue
File "Final2x_core\src\SRFactory\SRFactory.py", line 21, in getSR
> File "Final2x_core\src\SRFactory\REALCUGAN.py", line 9, in __init__
File "Final2x_core\src\SRFactory\REALCUGAN.py", line 54, in _init_SR_class
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 80, in __init__
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 98, in _set_parameters
RuntimeError: Caught an unknown exception!
2024-06-08 14:33:54.363 | ERROR    | Final2x_core.src.SRqueue:SR_queue:20 - An error has been caught in function 'SR_queue', process 'MainProcess' (6272), thread 'MainThread' (7236):
Traceback (most recent call last):
File "Final2x_core\__main__.py", line 82, in <module>
File "Final2x_core\__main__.py", line 73, in main
> File "Final2x_core\src\SRqueue.py", line 20, in SR_queue
File "Final2x_core\src\SRFactory\SRFactory.py", line 21, in getSR
File "Final2x_core\src\SRFactory\REALCUGAN.py", line 9, in __init__
File "Final2x_core\src\SRFactory\REALCUGAN.py", line 54, in _init_SR_class
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 80, in __init__
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 98, in _set_parameters
RuntimeError: Caught an unknown exception!
Traceback (most recent call last):
File "Final2x_core\__main__.py", line 82, in <module>
File "Final2x_core\__main__.py", line 73, in main
File "Final2x_core\src\SRqueue.py", line 20, in SR_queue
File "loguru\_logger.py", line 1277, in catch_wrapper
File "Final2x_core\src\SRFactory\SRFactory.py", line 21, in getSR
File "Final2x_core\src\SRFactory\REALCUGAN.py", line 9, in __init__
File "loguru\_logger.py", line 1277, in catch_wrapper
File "Final2x_core\src\SRFactory\REALCUGAN.py", line 54, in _init_SR_class
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 80, in __init__
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 98, in _set_parameters
RuntimeError: Caught an unknown exception!
[6272] Failed to execute script '__main__' due to unhandled exception!
CLOSE CODE:3221225477
```

**Comment by Tohrusky** [comment]
use GPU: Auto

**Comment by KlasFrosty** [comment]
Same.
```
[{"label":"CPU: Ryzen 5 3600X 6-Core Processor","value":-1},{"label":"GPU 0: Parsec Virtual Display Adapter","value":0},{"label":"GPU 1: NVIDIA GeForce GTX 1660 SUPER","value":1},{"label":"GPU: Auto","value":114514}]
{"gpuid":0,"inputpath":["C:\\Users\\bibim\\Downloads\\1716757013182.jpg"],"model":"RealCUGAN-se","modelscale":2,"modelnoise":1,"outputpath":"C:\\Users\\bibim\\Downloads","targetscale":0.6,"tta":false}
2024-06-10 21:23:04.678 | INFO     | __main__:main:55 - projectPATH: C:\Users\bibim\AppData\Local\Programs\Final2x\resources\app\resources\Final2x-core
2024-06-10 21:23:04.678 | INFO     | __main__:main:70 - config loaded
2024-06-10 21:23:04.678 | DEBUG    | __main__:main:71 - C:\Users\bibim\Downloads
2024-06-10 21:23:04.679 | INFO     | Final2x_core.src.SRFactory.SRBaseClass:_set_sr_n:50 - sr_n set to 1
2024-06-10 21:23:04.679 | INFO     | Final2x_core.src.SRFactory.SRBaseClass:__init__:32 - SRBaseClass init
vkCreateInstance failed -9
vkCreateInstance failed -9
2024-06-10 21:23:04.703 | ERROR    | Final2x_core.src.SRFactory.REALCUGAN:__init__:9 - An error has been caught in function '__init__', process 'MainProcess' (15064), thread 'MainThread' (12568):
Traceback (most recent call last):
File "Final2x_core\__main__.py", line 82, in <module>
File "Final2x_core\__main__.py", line 73, in main
File "Final2x_core\src\SRqueue.py", line 20, in SR_queue
File "Final2x_core\src\SRFactory\SRFactory.py", line 21, in getSR
> File "Final2x_core\src\SRFactory\REALCUGAN.py", line 9, in __init__
File "Final2x_core\src\SRFactory\REALCUGAN.py", line 54, in _init_SR_class
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 80, in __init__
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 98, in _set_parameters
RuntimeError: Caught an unknown exception!
2024-06-10 21:23:04.705 | ERROR    | Final2x_core.src.SRqueue:SR_queue:20 - An error has been caught in function 'SR_queue', process 'MainProcess' (15064), thread 'MainThread' (12568):
Traceback (most recent call last):
File "Final2x_core\__main__.py", line 82, in <module>
File "Final2x_core\__main__.py", line 73, in main
> File "Final2x_core\src\SRqueue.py", line 20, in SR_queue
File "Final2x_core\src\SRFactory\SRFactory.py", line 21, in getSR
File "Final2x_core\src\SRFactory\REALCUGAN.py", line 9, in __init__
File "Final2x_core\src\SRFactory\REALCUGAN.py", line 54, in _init_SR_class
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 80, in __init__
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 98, in _set_parameters
RuntimeError: Caught an unknown exception!
Traceback (most recent call last):
File "Final2x_core\__main__.py", line 82, in <module>
File "Final2x_core\__main__.py", line 73, in main
File "Final2x_core\src\SRqueue.py", line 20, in SR_queue
File "loguru\_logger.py", line 1277, in catch_wrapper
File "Final2x_core\src\SRFactory\SRFactory.py", line 21, in getSR
File "Final2x_core\src\SRFactory\REALCUGAN.py", line 9, in __init__
File "loguru\_logger.py", line 1277, in catch_wrapper
File "Final2x_core\src\SRFactory\REALCUGAN.py", line 54, in _init_SR_class
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 80, in __init__
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 98, in _set_parameters
RuntimeError: Caught an unknown exception!
[15064] Failed to execute script '__main__' due to unhandled exception!
CLOSE CODE:3221225477
```

**Comment by Tohrusky** [comment]
weird..  try turn off NVIDIA Optimus?

**Comment by KlasFrosty** [comment]
I think this is a laptop specific technology but I don't use a laptop.

> weird.. try turn off NVIDIA Optimus?

**Comment by ahming123** [comment]
[{"label":"CPU: Core™ i5-7400","value":-1},{"label":"GPU 0: NVIDIA GeForce GT 730","value":0},{"label":"GPU: Auto","value":114514}]
{"gpuid":0,"inputpath":["C:\\Users\\User\\Desktop\\wKgB4lJpJiGAKHI1ABIiz5QCr8s43.jpeg"],"model":"RealCUGAN-pro","modelscale":2,"modelnoise":0,"outputpath":"C:\\Users\\User\\Desktop","targetscale":0,"tta":true}
2024-07-22 20:14:11.587 | INFO     | _main_:main:60 - projectPATH: C:\Users\User\AppData\Local\Programs\Final2x\resources\app\resources\Final2x-core
2024-07-22 20:14:11.587 | INFO     | _main_:main:75 - config loaded
2024-07-22 20:14:11.587 | DEBUG    | _main_:main:76 - C:\Users\User\Desktop
2024-07-22 20:14:11.588 | INFO     | Final2x_core.src.SRFactory.SRBaseClass:_set_sr_n:50 - sr_n set to 1
2024-07-22 20:14:11.588 | INFO     | Final2x_core.src.SRFactory.SRBaseClass:_init_:32 - SRBaseClass init
[0 GeForce GT 730]  queueC=0[16]  queueG=0[16]  queueT=1[1]
[0 GeForce GT 730]  bugsbn1=0  bugbilz=3  bugcopc=0  bugihfa=0
[0 GeForce GT 730]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 GeForce GT 730]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
2024-07-22 20:14:12.711 | INFO     | Final2x_core.src.SRFactory.REALCUGAN:_init_SR_class:58 - RealCUGAN model initialized
2024-07-22 20:14:12.712 | INFO     | Final2x_core.src.SRqueue:SR_queue:22 - Processing------[ 0.0% ]
2024-07-22 20:14:12.732 | INFO     | Final2x_core.src.SRqueue:SR_queue:70 - Processing: C:\Users\User\Desktop\wKgB4lJpJiGAKHI1ABIiz5QCr8s43.jpeg, save to: C:\Users\User\Desktop\outputs\2x-wKgB4lJpJiGAKHI1ABIiz5QCr8s43.png
vkWaitForFences failed -4
vkQueueSubmit failed -4
vkQueueSubmit failed -4
vkQueueSubmit failed -4
vkAllocateMemory failed -2
2024-07-22 20:14:32.177 | ERROR    | Final2x_core.src.SRFactory.SRBaseClass:process:77 - An error has been caught in function 'process', process 'MainProcess' (17948), thread 'MainThread' (14968):
Traceback (most recent call last):
File "Final2x_core\_main_.py", line 87, in <module>
File "Final2x_core\_main_.py", line 78, in main
File "Final2x_core\src\SRqueue.py", line 71, in SR_queue
> File "Final2x_core\src\SRFactory\SRBaseClass.py", line 77, in process
File "Final2x_core\src\SRFactory\SRBaseClass.py", line 95, in _process_n
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 186, in process_cv2
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 128, in process
RuntimeError: Caught an unknown exception!
Traceback (most recent call last):
File "Final2x_core\_main_.py", line 87, in <module>
File "Final2x_core\_main_.py", line 78, in main
File "Final2x_core\src\SRqueue.py", line 81, in SR_queue
cv2.error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:1113: error: (-215:Assertion failed) !image.empty() in function 'cv::imencode'
[17948] Failed to execute script '_main_' due to unhandled exception!
CLOSE CODE:1

**Comment by ahming123** [comment]
can help me to check this tohrusky

**Comment by Tohrusky** [comment]
your gpu got no vulkan support https://developer.nvidia.com/vulkan-driver
plz try use cpu mode

**Comment by ahming123** [comment]
thanks tohrusky. really appreciated it

**Comment by Tohrusky** [comment]
Hello! your issue has been closed because it has been inactive for a long time.

你好，你的 issue 因为长时间不活跃而被自动关闭。

こんにちは、お問い合わせは長期間活動がないため、閉じられました。
