### ISSUE TITLE
Cannot start the render

### ISSUE THREAD

**Issue by ahming123** [Tohrusky/Final2x#523]
### Please carefully review each item in the checklist below | 请认真检查以下清单中的每一项 | 以下のチェックリストの各項目を注意深く確認してください

- [X] Searched and didn't find a similar issue | 已经搜索过，没有发现类似issue | 類似の問題が見つかりませんでした

### Is your feature request related to a problem? | 你的feature请求是否与一个问题有关？ | あなたのfeatureリクエストは質問に関連していますか？

Render failed

### Detail | 详细描述 | 詳細な説明

[{"label":"CPU: Core™ i5-7400","value":-1},{"label":"GPU 0: NVIDIA GeForce GT 730","value":0},{"label":"GPU: Auto","value":114514}]
{"gpuid":0,"inputpath":["C:\\Users\\User\\Desktop\\wKgB4lJpJiGAKHI1ABIiz5QCr8s43.jpeg"],"model":"RealCUGAN-pro","modelscale":2,"modelnoise":0,"outputpath":"C:\\Users\\User\\Desktop","targetscale":0,"tta":true}
2024-07-22 20:14:11.587 | INFO     | _main_:main:60 - projectPATH: C:\Users\User\AppData\Local\Programs\Final2x\resources\app\resources\Final2x-core
2024-07-22 20:14:11.587 | INFO     | _main_:main:75 - config loaded
2024-07-22 20:14:11.587 | DEBUG    | _main_:main:76 - C:\Users\User\Desktop
2024-07-22 20:14:11.588 | INFO     | Final2x_core.src.SRFactory.SRBaseClass:_set_sr_n:50 - sr_n set to 1
2024-07-22 20:14:11.588 | INFO     | Final2x_core.src.SRFactory.SRBaseClass:_init_:32 - SRBaseClass init
[0 GeForce GT 730]  queueC=0[16]  queueG=0[16]  queueT=1[1]
[0 GeForce GT 730]  bugsbn1=0  bugbilz=3  bugcopc=0  bugihfa=0
[0 GeForce GT 730]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 GeForce GT 730]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
2024-07-22 20:14:12.711 | INFO     | Final2x_core.src.SRFactory.REALCUGAN:_init_SR_class:58 - RealCUGAN model initialized
2024-07-22 20:14:12.712 | INFO     | Final2x_core.src.SRqueue:SR_queue:22 - Processing------[ 0.0% ]
2024-07-22 20:14:12.732 | INFO     | Final2x_core.src.SRqueue:SR_queue:70 - Processing: C:\Users\User\Desktop\wKgB4lJpJiGAKHI1ABIiz5QCr8s43.jpeg, save to: C:\Users\User\Desktop\outputs\2x-wKgB4lJpJiGAKHI1ABIiz5QCr8s43.png
vkWaitForFences failed -4
vkQueueSubmit failed -4
vkQueueSubmit failed -4
vkQueueSubmit failed -4
vkAllocateMemory failed -2
2024-07-22 20:14:32.177 | ERROR    | Final2x_core.src.SRFactory.SRBaseClass:process:77 - An error has been caught in function 'process', process 'MainProcess' (17948), thread 'MainThread' (14968):
Traceback (most recent call last):
File "Final2x_core\_main_.py", line 87, in <module>
File "Final2x_core\_main_.py", line 78, in main
File "Final2x_core\src\SRqueue.py", line 71, in SR_queue
> File "Final2x_core\src\SRFactory\SRBaseClass.py", line 77, in process
File "Final2x_core\src\SRFactory\SRBaseClass.py", line 95, in _process_n
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 186, in process_cv2
File "realcugan_ncnn_py\realcugan_ncnn_vulkan.py", line 128, in process
RuntimeError: Caught an unknown exception!
Traceback (most recent call last):
File "Final2x_core\_main_.py", line 87, in <module>
File "Final2x_core\_main_.py", line 78, in main
File "Final2x_core\src\SRqueue.py", line 81, in SR_queue
cv2.error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:1113: error: (-215:Assertion failed) !image.empty() in function 'cv::imencode'
[17948] Failed to execute script '_main_' due to unhandled exception!
CLOSE CODE:1

**Comment by Tohrusky** [comment]
Hello @ahming123, your issue has been closed because the title does not conform to our specification.

你好 @ahming123，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为标题不符合规范而被自动关闭。

こんにちは、@ahming123さん、タイトルが仕様に準拠していないため、ご提案いただいた問題はクローズされました。
