### ISSUE TITLE
[BUG]wrong again

### ISSUE THREAD

**Issue by mangic** [Tohrusky/Final2x#77]
### To reproduce | 复现步骤 | 再現方法
3. See error

### Context | 运行环境 | バックグラウンド
 - OS: [win10]
 - Arch: [e.g. x64]

### Error log | 报错日志 | ログ
```shell
0%
CPU: Core™ i7-4770
RealCUGAN-pro
2
0
Please Input
Please Input
C:\Users\Administrator\Downloads

Log
[{"label":"CPU: Core™ i7-4770","value":-1},{"label":"GPU 0: Intel(R) HD Graphics 4600","value":0},{"label":"GPU: Auto","value":114514}]
{"gpuid":-1,"inputpath":["C:\\Users\\Administrator\\Downloads\\微信图片_20230719074724.jpg"],"model":"RealCUGAN-pro","modelscale":2,"modelnoise":0,"outputpath":"C:\\Users\\Administrator\\Downloads","targetscale":null,"tta":false}
2023-07-19 07:48:41.720 | INFO     | __main__:main:58 - projectPATH: C:\Users\Administrator\AppData\Local\Programs\Final2x\resources\app\resources\Final2x-core
2023-07-19 07:48:41.720 | ERROR    | src.utils.getConfig:targetscale:125 - targetscale must be int or float
2023-07-19 07:48:41.721 | ERROR    | src.utils.getConfig:getConfigfromBase64toJson:61 - An error has been caught in function 'getConfigfromBase64toJson', process 'MainProcess' (7460), thread 'MainThread' (2240):
Traceback (most recent call last):
File "__main__.py", line 88, in <module>
File "__main__.py", line 63, in main
> File "src\utils\getConfig.py", line 61, in getConfigfromBase64toJson
File "src\utils\getConfig.py", line 73, in _setConfig
File "src\utils\getConfig.py", line 126, in targetscale
TypeError: targetscale must be int or float
2023-07-19 07:48:41.722 | ERROR    | __main__:main:63 - An error has been caught in function 'main', process 'MainProcess' (7460), thread 'MainThread' (2240):
Traceback (most recent call last):
File "__main__.py", line 88, in <module>
> File "__main__.py", line 63, in main
File "src\utils\getConfig.py", line 61, in getConfigfromBase64toJson
File "src\utils\getConfig.py", line 73, in _setConfig
File "src\utils\getConfig.py", line 126, in targetscale
TypeError: targetscale must be int or float
Traceback (most recent call last):
File "__main__.py", line 88, in <module>
File "__main__.py", line 63, in main
File "loguru\_logger.py", line 1251, in catch_wrapper
File "src\utils\getConfig.py", line 61, in getConfigfromBase64toJson
File "loguru\_logger.py", line 1251, in catch_wrapper
File "src\utils\getConfig.py", line 73, in _setConfig
File "src\utils\getConfig.py", line 126, in targetscale
TypeError: targetscale must be int or float
[7460] Failed to execute script '__main__' due to unhandled exception!
CLOSE CODE:1
```

### Additional context | 附加内容 | 追加コンテキスト
Add any other context and screenshots to help explain your problem.

**Comment by Tohrusky** [comment]
https://final2x.tohru.top/pages/guide/use.html#tooltip
Custom Scale should be a number so you should not set it to NULL. I will fix it.
